Feature/lc 3146 auto logout user after changing email
Civil-Service-Human-Resources/csl-identity-service pull request #102
Opened 2024-09-10 11:41 UTC by neeraj-jain-cbo

2024-09-30 13:01 UTC, jaylco requested changes

2024-10-01 12:21 UTC, neeraj-jain-cbo commented on src/main/resources/templates/emailupdate/updateEmailError.html
> +                    <li class="error-message">Please check the email update link.</li>
This implementation is removed from here and will be moved to a new ticket.

2024-10-01 12:37 UTC, neeraj-jain-cbo commented on src/main/resources/templates/emailupdate/emailUpdated.html
> +<script th:inline="javascript">
Done

2024-10-02 08:12 UTC, jaylco approved these changes

2024-10-02 08:13 UTC, merged